esphome:
  name: mira-showers
  friendly_name: Mira Showers

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: INFO

api:

ota:
  - platform: esphome

external_components:
  - source:
      type: git
      url: https://github.com/davidne0uk/esphome-miramode
      ref: v0.2.3
    components: [miramode]

esp32_ble_tracker:

ble_client:
  - mac_address: "DD:59:B9:5C:90:9F"
    id: ensuite_ble
  - mac_address: "EC:67:70:E5:C7:8A"
    id: master_bath_ble
  - mac_address: "E6:8E:D4:02:22:2E"
    id: master_shower_ble

miramode:
  - id: ensuite
    name: "Ensuite"
    client_name: "ESPHome"
    ble_client_id: ensuite_ble
    update_interval: 30s
    outlet1:
      name: "Ensuite Outlet 1"
    outlet2:
      name: "Ensuite Outlet 2"
    actual_temperature:
      name: "Ensuite Actual Temperature"
    target_temperature:
      name: "Ensuite Target Temperature"
      min_value: 20.0
      max_value: 48.0
      step: 0.5
    pair_button:
      name: "Pair Ensuite"
    unpair_button:
      name: "Unpair Ensuite"

  - id: master_bath
    name: "Master Bath"
    client_name: "ESPHome"
    ble_client_id: master_bath_ble
    update_interval: 30s
    outlet1:
      name: "Master Bath Outlet 1"
    outlet2:
      name: "Master Bath Outlet 2"
    actual_temperature:
      name: "Master Bath Actual Temperature"
    target_temperature:
      name: "Master Bath Target Temperature"
      min_value: 20.0
      max_value: 48.0
      step: 0.5
    pair_button:
      name: "Pair Master Bath"
    unpair_button:
      name: "Unpair Master Bath"

  - id: master_shower
    name: "Master Shower"
    client_name: "ESPHome"
    ble_client_id: master_shower_ble
    update_interval: 30s
    outlet1:
      name: "Master Shower Outlet 1"
    outlet2:
      name: "Master Shower Outlet 2"
    actual_temperature:
      name: "Master Shower Actual Temperature"
    target_temperature:
      name: "Master Shower Target Temperature"
      min_value: 20.0
      max_value: 48.0
      step: 0.5
    pair_button:
      name: "Pair Master Shower"
    unpair_button:
      name: "Unpair Master Shower"
